# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 11, 18 ]
        node-version: [ 16.x ]

    steps:
    - uses: actions/checkout@v3
      with:
        clean: false
        submodules: 'true'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: assets/package.json

    - name: Install Dependencies
      run: |
        cd assets
        pnpm install --no-frozen
        pnpm run build
        cd ..
    
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        mv assets/build/* src/main/resources/public/
        mvn package --file pom.xml
