# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        java-version: [ 11, 18 ]

    steps:
      - uses: actions/checkout@v3
        with:
          clean: false
          submodules: 'true'
          token: ${{ secrets.REPO_TOKEN }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: assets/package.json

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Build Frontend
        env:
          CI: false
        run: |
          cd assets/
          yarn install
          yarn build
          cd ../

      - name: Build with Maven
        run: |
          mv assets/build/* src/main/resources/public/
          mvn package --file pom.xml
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: application-release-${{ matrix.java-version }}
          path: target/Link-*.jar
